/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from "@gopowerteam/http-request";
import { Observable } from "rxjs";
import { DataDictController } from "@/config/controllers/manage-service/data-dict.controller";

export class DataDictService {
	/**
	 * 获取数据字典
	 */
	@Request({
		server: DataDictController.getAll,
	})
	public getAll(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 获取数据字典的hashCode
	 */
	@Request({
		server: DataDictController.getDataDictHashCode,
	})
	public getDataDictHashCode(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
}
