/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from "@gopowerteam/http-request";
import { Observable } from "rxjs";
import { DepartmentController } from "@/config/controllers/manage-service/department.controller";

export class DepartmentService {
	/**
	 * 新增部门
	 */
	@Request({
		server: DepartmentController.addDepartment,
	})
	public addDepartment(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 删除部门
	 */
	@Request({
		server: DepartmentController.deleteDepartment,
	})
	public deleteDepartment(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 获取全部部门
	 */
	@Request({
		server: DepartmentController.findAllDepartment,
	})
	public findAllDepartment(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 修改部门
	 */
	@Request({
		server: DepartmentController.modifyDepartment,
	})
	public modifyDepartment(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
}
