/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from "@gopowerteam/http-request";
import { Observable } from "rxjs";
import { ResourceController } from "@/config/controllers/manage-service/resource.controller";

export class ResourceService {
	/**
	 * 新增资源
	 */
	@Request({
		server: ResourceController.add,
	})
	public add(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 删除资源
	 */
	@Request({
		server: ResourceController.delete,
	})
	public delete(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 修改资源
	 */
	@Request({
		server: ResourceController.edit,
	})
	public edit(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 查询全部资源
	 */
	@Request({
		server: ResourceController.findAllResource,
	})
	public findAllResource(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
}
