/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from "@gopowerteam/http-request";
import { Observable } from "rxjs";
import { RoleController } from "@/config/controllers/manage-service/role.controller";

export class RoleService {
	/**
	 * 新增角色
	 */
	@Request({
		server: RoleController.addRole,
	})
	public addRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 批量分配角色
	 */
	@Request({
		server: RoleController.batchDistributeRole,
	})
	public batchDistributeRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 复制角色
	 */
	@Request({
		server: RoleController.copyRole,
	})
	public copyRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 删除角色
	 */
	@Request({
		server: RoleController.deleteRole,
	})
	public deleteRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 删除角色下用户
	 */
	@Request({
		server: RoleController.deleteRoleUser,
	})
	public deleteRoleUser(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 分配模块权限
	 */
	@Request({
		server: RoleController.distributePermission,
	})
	public distributePermission(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 用户分配角色
	 */
	@Request({
		server: RoleController.distributeRole,
	})
	public distributeRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 查询角色下所有控件资源
	 */
	@Request({
		server: RoleController.findAllControls,
	})
	public findAllControls(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 查询角色下所有菜单资源
	 */
	@Request({
		server: RoleController.findAllResource,
	})
	public findAllResource(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 多条件查询角色
	 */
	@Request({
		server: RoleController.findAllRole,
	})
	public findAllRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 获取所有角色
	 */
	@Request({
		server: RoleController.findRoles,
	})
	public findRoles(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 多条件角色下用户
	 */
	@Request({
		server: RoleController.findUserByRole,
	})
	public findUserByRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 获取所有角色
	 */
	@Request({
		server: RoleController.getAllRoles,
	})
	public getAllRoles(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
	/**
	 * 修改角色
	 */
	@Request({
		server: RoleController.modifyRole,
	})
	public modifyRole(requestParams: RequestParams): Observable<any> {
		return requestParams.request();
	}
}
