/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from "@gopowerteam/http-request";

// 控制器名称
const controller = "department";
const service = "manage";

export const DepartmentController = {
	// 新增部门
	addDepartment: {
		service,
		controller,
		path: "/api/department/addDepartment",
		action: "addDepartment",
		type: RequestMethod.Post,
	},
	// 删除部门
	deleteDepartment: {
		service,
		controller,
		path: "/api/department/deleteDepartment",
		action: "deleteDepartment",
		type: RequestMethod.Delete,
	},
	// 获取全部部门
	findAllDepartment: {
		service,
		controller,
		path: "/api/department/findAllDepartment",
		action: "findAllDepartment",
		type: RequestMethod.Get,
	},
	// 修改部门
	modifyDepartment: {
		service,
		controller,
		path: "/api/department/modifyDepartment",
		action: "modifyDepartment",
		type: RequestMethod.Put,
	},
};
