/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from "@gopowerteam/http-request";

// 控制器名称
const controller = "resource";
const service = "manage";

export const ResourceController = {
	// 新增资源
	add: {
		service,
		controller,
		path: "/api/resource/add",
		action: "add",
		type: RequestMethod.Post,
	},
	// 删除资源
	delete: {
		service,
		controller,
		path: "/api/resource/delete",
		action: "delete",
		type: RequestMethod.Delete,
	},
	// 修改资源
	edit: {
		service,
		controller,
		path: "/api/resource/edit",
		action: "edit",
		type: RequestMethod.Post,
	},
	// 查询全部资源
	findAllResource: {
		service,
		controller,
		path: "/api/resource/findAllResource",
		action: "findAllResource",
		type: RequestMethod.Get,
	},
};
