/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from "@gopowerteam/http-request";

// 控制器名称
const controller = "role";
const service = "manage";

export const RoleController = {
	// 新增角色
	addRole: {
		service,
		controller,
		path: "/api/role/addRole",
		action: "addRole",
		type: RequestMethod.Post,
	},
	// 批量分配角色
	batchDistributeRole: {
		service,
		controller,
		path: "/api/role/batchDistributeRole",
		action: "batchDistributeRole",
		type: RequestMethod.Post,
	},
	// 复制角色
	copyRole: {
		service,
		controller,
		path: "/api/role/copyRole",
		action: "copyRole",
		type: RequestMethod.Get,
	},
	// 删除角色
	deleteRole: {
		service,
		controller,
		path: "/api/role/deleteRole",
		action: "deleteRole",
		type: RequestMethod.Delete,
	},
	// 删除角色下用户
	deleteRoleUser: {
		service,
		controller,
		path: "/api/role/deleteRoleUser",
		action: "deleteRoleUser",
		type: RequestMethod.Put,
	},
	// 分配模块权限
	distributePermission: {
		service,
		controller,
		path: "/api/role/distributePermission",
		action: "distributePermission",
		type: RequestMethod.Post,
	},
	// 用户分配角色
	distributeRole: {
		service,
		controller,
		path: "/api/role/distributeRole",
		action: "distributeRole",
		type: RequestMethod.Post,
	},
	// 查询角色下所有控件资源
	findAllControls: {
		service,
		controller,
		path: "/api/role/findAllControls",
		action: "findAllControls",
		type: RequestMethod.Get,
	},
	// 查询角色下所有菜单资源
	findAllResource: {
		service,
		controller,
		path: "/api/role/findAllResource",
		action: "findAllResource",
		type: RequestMethod.Get,
	},
	// 多条件查询角色
	findAllRole: {
		service,
		controller,
		path: "/api/role/findAllRole",
		action: "findAllRole",
		type: RequestMethod.Get,
	},
	// 获取所有角色
	findRoles: {
		service,
		controller,
		path: "/api/role/findRoles",
		action: "findRoles",
		type: RequestMethod.Get,
	},
	// 多条件角色下用户
	findUserByRole: {
		service,
		controller,
		path: "/api/role/findUserByRole",
		action: "findUserByRole",
		type: RequestMethod.Get,
	},
	// 获取所有角色
	getAllRoles: {
		service,
		controller,
		path: "/api/role/getAllRoles",
		action: "getAllRoles",
		type: RequestMethod.Get,
	},
	// 修改角色
	modifyRole: {
		service,
		controller,
		path: "/api/role/modifyRole",
		action: "modifyRole",
		type: RequestMethod.Put,
	},
};
