/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from "@gopowerteam/http-request";

// 控制器名称
const controller = "system-log";
const service = "manage";

export const SystemLogController = {
	// 批量删除登录日志
	batchDeleteLog: {
		service,
		controller,
		path: "/api/systemLog/batchDeleteLog",
		action: "batchDeleteLog",
		type: RequestMethod.Delete,
	},
	// 系统日志查询
	findAllSystemLog: {
		service,
		controller,
		path: "/api/systemLog/list",
		action: "findAllSystemLog",
		type: RequestMethod.Get,
	},
	// 新增日志
	saveSystemLog: {
		service,
		controller,
		path: "/api/systemLog/saveSystemLog",
		action: "saveSystemLog",
		type: RequestMethod.Post,
	},
};
