/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from "@gopowerteam/http-request";

// 控制器名称
const controller = "user";
const service = "manage";

export const UserController = {
	// 新增用户
	addUser: {
		service,
		controller,
		path: "/api/user/addUser",
		action: "addUser",
		type: RequestMethod.Post,
	},
	// APP用户登录
	appLogin: {
		service,
		controller,
		path: "/api/user/appLogin",
		action: "appLogin",
		type: RequestMethod.Post,
	},
	// 通过id删除用户
	deleteUserById: {
		service,
		controller,
		path: "/api/user/deleteUserById",
		action: "deleteUserById",
		type: RequestMethod.Delete,
	},
	// 多条件查询用户
	findUserByDepartment: {
		service,
		controller,
		path: "/api/user/findUserByDepartment",
		action: "findUserByDepartment",
		type: RequestMethod.Get,
	},
	// 根据部门code查询用户
	findUserByDepartmentCode: {
		service,
		controller,
		path: "/api/user/findUserByDepartmentCode",
		action: "findUserByDepartmentCode",
		type: RequestMethod.Get,
	},
	// 查询用户所分配角色
	getRoles: {
		service,
		controller,
		path: "/api/user/getRoles",
		action: "getRoles",
		type: RequestMethod.Get,
	},
	// 通过token获取用户
	getUserByToken: {
		service,
		controller,
		path: "/api/user/getUserByToken/{token}",
		action: "getUserByToken",
		type: RequestMethod.Get,
	},
	// 通过Id获取用户职位状态
	getUserStateById: {
		service,
		controller,
		path: "/api/user/getUserStateById",
		action: "getUserStateById",
		type: RequestMethod.Get,
	},
	// 用户登录
	login: {
		service,
		controller,
		path: "/api/user/login",
		action: "login",
		type: RequestMethod.Post,
	},
	// 用户登出
	logout: {
		service,
		controller,
		path: "/api/user/logout",
		action: "logout",
		type: RequestMethod.Get,
	},
	// 修改用户
	modifyUser: {
		service,
		controller,
		path: "/api/user/modifyUser",
		action: "modifyUser",
		type: RequestMethod.Put,
	},
	// 重置/修改密码
	resetPassword: {
		service,
		controller,
		path: "/api/user/resetPassword",
		action: "resetPassword",
		type: RequestMethod.Put,
	},
	// 更新密码
	updatePassword: {
		service,
		controller,
		path: "/api/user/updatePassword",
		action: "updatePassword",
		type: RequestMethod.Post,
	},
};
